alias: Lights off set sleep time on UpStar
initial_state: True
hide_entity: False
trigger:
  platform: state
  entity_id: switch.lamp
  from: 'on'
  to: 'off'
condition:
- condition: state
  entity_id: sun.sun
  state: 'below_horizon'
action:
- service: switch.turn_on
  entity_id: switch.sleep
- service: switch.turn_on
  entity_id: switch.sleep
- service: switch.turn_on
  entity_id: switch.sleep
- service: switch.turn_off
  entity_id: switch.sleep
