alias: Turn on front door & tree lights when sun sets
initial_state: True
hide_entity: False
trigger:
  platform: sun
  event: sunset
action:
- service: light.turn_on
  entity_id: light.front_door_light
- service: switch.turn_on
  entity_id: switch.tree_lights  
