alias: Turn off tree light when sun rises
trigger:
    platform: sun
    event: sunrise
action:
- service: switch.turn_off
  entity_id: switch.tree_lights
- service: light.turn_off
  entity_id: light.front_door_light
