  entities:
    - name: Home Assistant
      url: https://home-assistant.io
    - name: ZoneMinder
      url: http://hive/zm
    - name: Update Desk Cam
      url: http://192.168.0.109/snapshot.cgi
    - name: CDRBLK
      url: https://cdrblk.com
    - name: Chronic Tracker
      url: https://chronictrackers.com
    - name: HELP
      url: https://help.davedaley.com:10000/
    - name: OVH
      url: https://ovh.davedaley.com:10000
    - name: docker
      url: https://docker.davedaley.com:10000  
    - name: prime.optincall.com
      url: https://prime.optincall.com:10000
    - name: Chronic Tracker
      url: https://chronictrackers.com
    - name: CannaBlissCream
      url: https://cannablisscream.com
    - name: cart.chronictrackers.com
      url: https://cart.chronictrackers.com
    - name: Flash Hunt
      url: https://flashhunt.com
    - name: Froggy Farms
      url: https://froggyfarms.com
    - name: Baked with Buddies
      url: https://bakedwithbuddies.com
    - name: Armbar Assassin
      url: https://armbarassassin.com
    - name: Auntie Ks Kitchen
      url: https://auntiekskitchen.com
    - name: pinheadztradingpost.com
      url: https://pinheadztradingpost.com
    - name: simplyeffectsmakeup.com
      url: https://simplyeffectsmakeup.com
    - name: cannadiamond.com
      url: https://cannadiamond.com
    - name: secure.optincall.com
      url: https://secure.optincall.com
